"""Copy the parts of data/ the frontend needs into frontend/mocks/ as JSON.

Run after changing stations.yaml, lines.yaml, travellers.json or pois.json:
    python scripts/export_frontend_data.py
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "frontend" / "mocks"


def dump(name: str, payload: dict) -> None:
    payload = {"_note": f"GENERATED by scripts/export_frontend_data.py from data/ — do not edit by hand.", **payload}
    (OUT / name).write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")


def main() -> None:
    stations = yaml.safe_load((DATA / "network/stations.yaml").read_text())["stations"]
    network = yaml.safe_load((DATA / "network/lines.yaml").read_text())
    travellers = json.loads((DATA / "travellers.json").read_text())["travellers"]
    pois = json.loads((DATA / "pois.json").read_text())["pois"]

    dump("stations.json", {"stations": {
        s["id"]: {"name": s["name"], "mode": s["mode"], "lat": s["lat"], "lon": s["lon"],
                  "step_free": s.get("step_free", False)}
        for s in stations}})
    dump("lines.json", {"lines": {
        line["id"]: {"name": line["name"], "mode": line["mode"], "color": line.get("color", "#888888"),
                     "stations": line["stations"]}
        for line in network["lines"]}})
    dump("travellers.json", {"travellers": travellers})
    dump("pois.json", {"pois": {p["id"]: {"name": p["name"], "lat": p["lat"], "lon": p["lon"]} for p in pois}})
    print(f"Exported {len(stations)} stations, {len(network['lines'])} lines, "
          f"{len(travellers)} travellers, {len(pois)} POIs to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
